version: "3"
services:
  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    logging:
      driver: "none"

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    logging:
      driver: "none"
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  
  wdio-test:
    build: .
    container_name: weatherapp_test
    depends_on:
      - selenium-hub
      - chrome
    network_mode: host
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
  
